### ISSUE TITLE
No module named 'video_source'

### ISSUE THREAD

**Issue by playaspec** [stepacool/Eye-Tracker#16]
Ran into a few snags trying to get the requirements installed on Ubuntu 20.04. After creating the venv, poetry failed to find Qt6. Updating pip with `python -m pip install --upgrade pip` then running poetry did the trick, however when running the tracker I get:

```
(venv) playaspec@Cortex1:~/Documents/Programming/Eye-Tracker/project$ python main.py 
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from gui.application_window import Window
  File "/Users/playaspec/Documents/Programming/Eye-Tracker/project/gui/application_window.py", line 8, in <module>
    from video_source import FrameSource
ModuleNotFoundError: No module named 'video_source'
```
I've also tried cloning the repo into a Conda environment. Both venvs have difficulty finding Qt6 or the right opencv. Is there a missing requirement or environment variable that's preventing the module from being found?

**Comment by stepacool** [comment]
just fixed it, thanks for noticing. I made a mistake when squashing.

**Comment by playaspec** [comment]
Lol. I deleted it and re-cloned it just to make sure I didn't muck up the venv and it worked. _THEN_ I noticed you replied! Confirmed working now. Now to get the data out to a DAC!
