### ISSUE TITLE
Couldnt place red circle around pupil

### ISSUE THREAD

**Issue by Hamid-Nazir** [stepacool/Eye-Tracker#4]
Working perfectly. But there is a problem. 
When i select the "Blob" slider, the blob does not appear or just appear on the right eye.
And when i select the circle option slider, circle appears on both eyes but are not so correct. 
Please help me out as soon as possible that How can i get correct blob and circle as your appeared in the Youtube video.

Thanks.
![1](https://user-images.githubusercontent.com/47783326/53286633-5490b280-3793-11e9-9c0e-93ea6f0af3f2.PNG)
![2](https://user-images.githubusercontent.com/47783326/53286634-5490b280-3793-11e9-8227-1842cb676704.PNG)

**Comment by stepacool** [comment]
Hello, although the blob method is a little more precise, it's more
sensitive to light. So if your eyes are too different in terms of lighting,
only one eye might be detected. Just drag the slider around until you find
the balance, it'll work.

Thanks for taking a look at my projects.

**Comment by Hamid-Nazir** [comment]
You really worked great.
