### ISSUE TITLE
Not working/detecting  with eyeGlasses.

### ISSUE THREAD

**Issue by SaddamBInSyed** [stepacool/Eye-Tracker#8]
thanks for the great work.

by the way, I have tested the same with an eyeglass and without but it only works with without eyeglasses.

with eye glasses, it not at all detecting the eyes 

Note:
i have included the eyeglass HAAR xml file but NO LUCK

**Comment by stepacool** [comment]
Hello, it depends on what kind of glasses you wear. If they don't cover your eyes, you just have to adjust lighting. If they do, you have to use HAAR for glasses.
